### ISSUE TITLE
center text?

### ISSUE THREAD

**Issue by sunsgs** [kartsims/easysvg#12]
Hi there, i will use your paths inside a common svg container. I need to center the text. Can i generate the svg with 100% height and width and then center the text inside?

**Comment by kartsims** [comment]
Hi
Please provide a gist, I don't think I totally understand...

**Comment by sunsgs** [comment]
Hi, i don't have a gist now. Basically what i need to do is to have an svg (400x300) and center vertically and horizontally the text in it. not 0 0

**Comment by kartsims** [comment]
How about improving the `addText($text, $x, $y, $attributes=array())` method to allow `center` to be passed as a string for `$x` and `$y` ? 

You would have to write `$svg->addText($my_text, "center", "center")`.

This is feasible but it would require to call `$svg->addAttribute("width", $svg_width)` before the `addText` method. Otherwise it would throw an error.

Would that cover your need ?

**Comment by sunsgs** [comment]
it seems to be not working : https://gist.github.com/sunsgs/2bd4206648030d7fdd1d7a2ca1caa183

**Comment by kartsims** [comment]
This is a proposal.

If doing that covers your need, then I'll have to update the code to make it working.

Please let me know first if that would cover your need

**Comment by kartsims** [comment]
master branch has been updated, please try again your Gist, it should work

**Comment by sunsgs** [comment]
Thanks, but it seems to be not well centered. Am I wrong?

**Comment by kartsims** [comment]
It is centered according to the font definition, which handles a line height, see the first image in this picture.

![Font lines](https://www.w3.org/TR/2002/WD-css3-linebox-20020515/Baselines-HorizAndVert-ApCountry.gif)

There may be a way but I don't know how to handle the glyphs with those. I am no typo expert unfortunately.

**Comment by brianwozeniak** [comment]
I realize you closed this, but I am also having problems centering text vertically. Horizontally it seems fairly good. When I look at your textDimensions method I am a little confused on exactly what this calculation does:

```
$lineHeight = ( $this->font->ascent + $this->font->descent ) * $fontSize * 2;
```

After looking at what comes in with fonts, the Font Ascent which would be the top of the font is usually a positive number, while the Font Descent which is the bottom of the font is a negative number. Thus if you have 1 and -1 they would cancel out to be a line height of zero? Are you actually needing to subtract these numbers or at least take the absolute value of them? Why is this all multiplied by 2 also? I am just trying to understand where these numbers come from so that I can help fix the vertical alignment centering issue which is not correct, at least for me. So far this line is standing out to me as part of the issue.
