### ISSUE TITLE
Need help with your Library

### ISSUE THREAD

**Issue by DannyDan** [kartsims/easysvg#15]
Hi there,
sorry for get in touch with you via this way.
I'm using this awesome library for generating a path with text. Is it possible to manipulate the created path for example mirroring text, aligning text or changing the ratio?
Thank you.

Danny

**Comment by kartsims** [comment]
Hi,

No worries. I don't know how to mirror, or change the ratio in the path itself but in case you didn't know already, you can use `transform` attributes on the `path` object ([example](https://stackoverflow.com/questions/13898292/mirroring-a-path-in-svg))

I hope this helps. I am not a specialist of SVG so you may ask on SO otherwise.

Cheers,
Simon

**Comment by DannyDan** [comment]
Hey Simon,
thanks for this fast answer! I already played with the transform attribute of the path but I need to set the path itself.
I try my luck @ SO.

Thanks again.
Danny

**Comment by kartsims** [comment]
If that may help, I made the library using "matrix transformations" found from another language (can't remember which, sorry). They might even be "abstract" SVG docs.

If you find a matrix corresponding to mirroring for instance (I am sure there is one for this), you should be able to apply it the same way it's done with the others.

Good luck with that and feel free to send a PR if you manage to do these ;)

++
Simon
