### ISSUE TITLE
color code letters

### ISSUE THREAD

**Issue by iBasit** [kartsims/easysvg#6]
I wanted to color code letters and create them into word by word like following example.

can this library can do this?

![image](https://cloud.githubusercontent.com/assets/34341/13253333/7dc3194c-da33-11e5-9c01-fe06751be314.png)

**Comment by kartsims** [comment]
You can do so but it requires some advanced usage of the library. You would :
- create the first colored set of characters
- measure its width, store this width as `$offset` for instance
- create the second set of characters
- translate it horizontally using the `$offset` value
- append it to the SVG file
- measure the 2nd set's width, and add it to `$offset`
- etc.

I realize this is not optimal but it could do it. If you need help implementing this let me know.

Also note that the library hasn't been thought for right-to-left writing but it would be easy to change it... You may give it a try if you want (it should be about adding a minus instead of a plus here and there) or let me know what you need in a separate issue

**Comment by iBasit** [comment]
Would you consider charging small fee for creating a function that will parse and generate svg file?
