### ISSUE TITLE
How about font style like Bold, Underline, Itatic, LineThrough

### ISSUE THREAD

**Issue by magebay99** [kartsims/easysvg#9]
Thank you for sharing nice script. I just wonder how about the font style? 

Thank you.
Calvin

**Comment by kartsims** [comment]
Unfortunately, this requires some deep calculations because we are working on the plain glyph (ie font character) extracted from the SVG file.

I'll leave this issue open if anyone knows how to apply italic/bold transformation to an SVG path... but I really have no clue about how this can be done programmatically.
